# This YAML file contains nginx & csi cinder driver objects,
# which are necessary to run nginx with csi cinder driver.

# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: rook-ceph-block
# provisioner: io.edgefs.csi.nfs
# parameters:
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openeb-mayastor-iscsi-csi-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mayastor-iscsi

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx 
spec:
  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    volumeMounts:
      - mountPath: /var/lib/www/html
        name: openeb-mayastor-iscsi-csi-volume 
  volumes:
  - name: openeb-mayastor-iscsi-csi-volume
    persistentVolumeClaim:
      claimName: openeb-mayastor-iscsi-csi-pvc
      readOnly: false